const movieDataMock = {
	movie: {
		popular: {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
					genre_ids: [14, 35, 10751],
					id: 642885,
					original_language: "en",
					original_title: "Hocus Pocus 2",
					overview:
						"It’s been 29 years since someone lit the Black Flame Candle and resurrected the 17th-century sisters, and they are looking for revenge. Now it is up to three high-school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow’s Eve.",
					popularity: 5947.971,
					poster_path: "/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg",
					release_date: "2022-09-27",
					title: "Hocus Pocus 2",
					video: false,
					vote_average: 7.9,
					vote_count: 511,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
					genre_ids: [27, 53],
					id: 760161,
					original_language: "en",
					original_title: "Orphan: First Kill",
					overview:
						"After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
					popularity: 5744.797,
					poster_path: "/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg",
					release_date: "2022-07-27",
					title: "Orphan: First Kill",
					video: false,
					vote_average: 6.9,
					vote_count: 915,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg",
					genre_ids: [28, 35, 53],
					id: 718930,
					original_language: "en",
					original_title: "Bullet Train",
					overview:
						"Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
					popularity: 4647.01,
					poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
					release_date: "2022-07-03",
					title: "Bullet Train",
					video: false,
					vote_average: 7.5,
					vote_count: 1544,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/cOF0InT1qQVUeNjqxjF7gtEtL5L.jpg",
					genre_ids: [53],
					id: 985939,
					original_language: "en",
					original_title: "Fall",
					overview:
						"For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights",
					popularity: 4672.324,
					poster_path: "/spCAxD99U1A6jsiePFoqdEcY0dG.jpg",
					release_date: "2022-08-11",
					title: "Fall",
					video: false,
					vote_average: 7.4,
					vote_count: 1277,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/7AiIrnDMaOhPrw9elJ5NNjijTW4.jpg",
					genre_ids: [53],
					id: 916605,
					original_language: "en",
					original_title: "The Infernal Machine",
					overview:
						"Reclusive and controversial author Bruce Cogburn is drawn out of hiding by an obsessive fan, forcing the novelist to confront a past that he thought he could escape, and to account for events set in motion by his bestseller decades earlier. Cogburn's search for who is behind the manipulation and mental torment he encounters leads to an emotional roller-coaster ride full of fear and danger, where things are not always as clear as they seem to be, and where past deeds can have dire consequences.",
					popularity: 3604.893,
					poster_path: "/bSqpOGzaKBdGkBLmcm1JJIVryYy.jpg",
					release_date: "2022-09-23",
					title: "The Infernal Machine",
					video: false,
					vote_average: 6.8,
					vote_count: 50,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/rgZ3hdzgMgYgzvBfwNEVW01bpK1.jpg",
					genre_ids: [28, 53],
					id: 429473,
					original_language: "en",
					original_title: "Lou",
					overview:
						"A young girl is kidnapped during a powerful storm. Her mother joins forces with her mysterious neighbour to set off in pursuit of the kidnapper. Their journey will test their limits and expose the dark secrets of their past.",
					popularity: 3166.073,
					poster_path: "/djM2s4wSaATn4jVB33cV05PEbV7.jpg",
					release_date: "2022-09-23",
					title: "Lou",
					video: false,
					vote_average: 6.5,
					vote_count: 208,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/ghsPsvM0sEztdNT4kUlTsBF2LEF.jpg",
					genre_ids: [18, 28, 53],
					id: 852046,
					original_language: "fr",
					original_title: "Athena",
					overview:
						"Hours after the tragic death of their youngest brother in unexplained circumstances, three siblings have their lives thrown into chaos.",
					popularity: 2921.268,
					poster_path: "/fenNPxVF5ERy0CSyVruuEg959Hg.jpg",
					release_date: "2022-09-09",
					title: "Athena",
					video: false,
					vote_average: 6.6,
					vote_count: 213,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
					genre_ids: [10749, 18],
					id: 744276,
					original_language: "en",
					original_title: "After Ever Happy",
					overview:
						"As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
					popularity: 2785.246,
					poster_path: "/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg",
					release_date: "2022-08-24",
					title: "After Ever Happy",
					video: false,
					vote_average: 6.9,
					vote_count: 316,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
					genre_ids: [14, 12, 10751],
					id: 532639,
					original_language: "en",
					original_title: "Pinocchio",
					overview:
						"A wooden puppet embarks on a thrilling adventure to become a real boy.",
					popularity: 2436.699,
					poster_path: "/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg",
					release_date: "2022-09-07",
					title: "Pinocchio",
					video: false,
					vote_average: 6.7,
					vote_count: 853,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/2k9tBql5GYH328Krj66tDT9LtFZ.jpg",
					genre_ids: [12, 18, 27],
					id: 760741,
					original_language: "en",
					original_title: "Beast",
					overview:
						"A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
					popularity: 2418.176,
					poster_path: "/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg",
					release_date: "2022-08-11",
					title: "Beast",
					video: false,
					vote_average: 7.1,
					vote_count: 596,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/5hoS3nEkGGXUfmnu39yw1k52JX5.jpg",
					genre_ids: [28, 12, 14],
					id: 960704,
					original_language: "ja",
					original_title: "鋼の錬金術師 完結編 最後の錬成",
					overview:
						"The Elric brothers’ long and winding journey comes to a close in this epic finale, where they must face off against an unworldly, nationwide threat.",
					popularity: 2191.622,
					poster_path: "/AeyiuQUUs78bPkz18FY3AzNFF8b.jpg",
					release_date: "2022-06-24",
					title: "Fullmetal Alchemist: The Final Alchemy",
					video: false,
					vote_average: 7,
					vote_count: 33,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/mVNPfpydornVe4H4UCIk7WevWjf.jpg",
					genre_ids: [27, 9648, 53],
					id: 882598,
					original_language: "en",
					original_title: "Smile",
					overview:
						"After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
					popularity: 2015.942,
					poster_path: "/hiaeZKzwsk4y4atFhmncO5KRxeT.jpg",
					release_date: "2022-09-23",
					title: "Smile",
					video: false,
					vote_average: 6.8,
					vote_count: 128,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
					genre_ids: [14, 28, 35],
					id: 616037,
					original_language: "en",
					original_title: "Thor: Love and Thunder",
					overview:
						"After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
					popularity: 1920.283,
					poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
					release_date: "2022-07-06",
					title: "Thor: Love and Thunder",
					video: false,
					vote_average: 6.8,
					vote_count: 4085,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/qaTzVAW1u16WFNsepjCrilBuInc.jpg",
					genre_ids: [16, 28, 10751, 35, 878],
					id: 539681,
					original_language: "en",
					original_title: "DC League of Super-Pets",
					overview:
						"When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
					popularity: 1772.214,
					poster_path: "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
					release_date: "2022-07-27",
					title: "DC League of Super-Pets",
					video: false,
					vote_average: 7.5,
					vote_count: 755,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
					genre_ids: [53, 28, 878],
					id: 766507,
					original_language: "en",
					original_title: "Prey",
					overview:
						"When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
					popularity: 1718.925,
					poster_path: "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
					release_date: "2022-08-02",
					title: "Prey",
					video: false,
					vote_average: 7.9,
					vote_count: 4227,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
					genre_ids: [16, 10751],
					id: 438148,
					original_language: "en",
					original_title: "Minions: The Rise of Gru",
					overview:
						"A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
					popularity: 1619.547,
					poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
					release_date: "2022-06-29",
					title: "Minions: The Rise of Gru",
					video: false,
					vote_average: 7.6,
					vote_count: 2122,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
					genre_ids: [28, 18, 878],
					id: 629176,
					original_language: "en",
					original_title: "Samaritan",
					overview:
						"Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
					popularity: 1568.275,
					poster_path: "/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg",
					release_date: "2022-08-25",
					title: "Samaritan",
					video: false,
					vote_average: 6.9,
					vote_count: 1246,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
					genre_ids: [16, 878, 28],
					id: 610150,
					original_language: "ja",
					original_title: "ドラゴンボール超 スーパーヒーロー",
					overview:
						"The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
					popularity: 1538.979,
					poster_path: "/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
					release_date: "2022-06-11",
					title: "Dragon Ball Super: Super Hero",
					video: false,
					vote_average: 8,
					vote_count: 1844,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/3PieOs1t6dPHWlgvX3XoqTIQLqN.jpg",
					genre_ids: [12, 28, 878],
					id: 507086,
					original_language: "en",
					original_title: "Jurassic World Dominion",
					overview:
						"Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
					popularity: 1471.02,
					poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
					release_date: "2022-06-01",
					title: "Jurassic World Dominion",
					video: false,
					vote_average: 7,
					vote_count: 3566,
					media_type: "movie",
				},
				{
					adult: false,
					backdrop_path: "/5EzpTMkpg3DecNoP2DAOBlh0Fi6.jpg",
					genre_ids: [28, 80],
					id: 993145,
					original_language: "en",
					original_title: "Bullet Proof",
					overview:
						"The Thief  pulls off the robbery of a lifetime when he robs the psychotic drug lord, Temple. The plan goes off without a hitch until the Thief discovers a stowaway in his getaway car - Temple's pregnant wife, Mia.",
					popularity: 1459.074,
					poster_path: "/cj6YmTAU7Jvn3w6d2NfjQzpX7Pw.jpg",
					release_date: "2022-08-19",
					title: "Bullet Proof",
					video: false,
					vote_average: 4.7,
					vote_count: 12,
					media_type: "movie",
				},
			],
			total_pages: 35379,
			total_results: 707574,
			media_type: "movie",
		},
		genres: [
			{
				id: 28,
				name: "Action",
			},
			{
				id: 12,
				name: "Adventure",
			},
			{
				id: 16,
				name: "Animation",
			},
			{
				id: 35,
				name: "Comedy",
			},
			{
				id: 80,
				name: "Crime",
			},
			{
				id: 99,
				name: "Documentary",
			},
			{
				id: 18,
				name: "Drama",
			},
			{
				id: 10751,
				name: "Family",
			},
			{
				id: 14,
				name: "Fantasy",
			},
			{
				id: 36,
				name: "History",
			},
			{
				id: 27,
				name: "Horror",
			},
			{
				id: 10402,
				name: "Music",
			},
			{
				id: 9648,
				name: "Mystery",
			},
			{
				id: 10749,
				name: "Romance",
			},
			{
				id: 878,
				name: "Science Fiction",
			},
			{
				id: 10770,
				name: "TV Movie",
			},
			{
				id: 53,
				name: "Thriller",
			},
			{
				id: 10752,
				name: "War",
			},
			{
				id: 37,
				name: "Western",
			},
		],
	},
	tv: {
		popular: {
			page: 1,
			results: [
				{
					backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
					first_air_date: "2022-09-21",
					genre_ids: [18, 80],
					id: 113988,
					name: "Dahmer – Monster: The Jeffrey Dahmer Story",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
					overview:
						"Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?",
					popularity: 9719.599,
					poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
					vote_average: 8.4,
					vote_count: 673,
					media_type: "tv",
				},
				{
					backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
					first_air_date: "2022-09-01",
					genre_ids: [10765, 10759, 18],
					id: 84773,
					name: "The Lord of the Rings: The Rings of Power",
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Lord of the Rings: The Rings of Power",
					overview:
						"Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
					popularity: 5653.246,
					poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
					vote_average: 7.7,
					vote_count: 970,
					media_type: "tv",
				},
				{
					backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
					first_air_date: "2022-08-21",
					genre_ids: [10765, 18, 10759],
					id: 94997,
					name: "House of the Dragon",
					origin_country: ["US"],
					original_language: "en",
					original_name: "House of the Dragon",
					overview:
						"The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
					popularity: 5631.599,
					poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
					vote_average: 8.6,
					vote_count: 1638,
					media_type: "tv",
				},
				{
					backdrop_path: "/eljErfkQUcFUgQkI4I1soZcH8MW.jpg",
					first_air_date: "2022-08-18",
					genre_ids: [35, 10765],
					id: 92783,
					name: "She-Hulk: Attorney at Law",
					origin_country: ["US"],
					original_language: "en",
					original_name: "She-Hulk: Attorney at Law",
					overview:
						"Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
					popularity: 3661.228,
					poster_path: "/3qO7wycn6o0lUJf15dupMFbEBTY.jpg",
					vote_average: 7,
					vote_count: 905,
					media_type: "tv",
				},
				{
					backdrop_path: "/pysGisnLhmjQB2CGQCAQDxBADsH.jpg",
					first_air_date: "2021-10-12",
					genre_ids: [80, 10765],
					id: 90462,
					name: "Chucky",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Chucky",
					overview:
						"After a vintage Chucky doll turns up at a suburban yard sale, an idyllic American town is thrown into chaos as a series of horrifying murders begin to expose the town’s hypocrisies and secrets. Meanwhile, the arrival of enemies — and allies — from Chucky’s past threatens to expose the truth behind the killings, as well as the demon doll’s untold origins.",
					popularity: 2266.416,
					poster_path: "/kY0BogCM8SkNJ0MNiHB3VTM86Tz.jpg",
					vote_average: 7.9,
					vote_count: 3267,
					media_type: "tv",
				},
				{
					backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
					first_air_date: "2013-12-02",
					genre_ids: [16, 35, 10765, 10759],
					id: 60625,
					name: "Rick and Morty",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Rick and Morty",
					overview:
						"Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
					popularity: 1906.325,
					poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
					vote_average: 8.7,
					vote_count: 7160,
					media_type: "tv",
				},
				{
					backdrop_path: "/kOkmTrD8kWLeTXcAEwctg6GwW7t.jpg",
					first_air_date: "2017-02-20",
					genre_ids: [10751, 35],
					id: 91759,
					name: "Come Home Love: Lo and Behold",
					origin_country: ["HK"],
					original_language: "cn",
					original_name: "愛·回家之開心速遞",
					overview:
						"Hung Sue Gan starting from the bottom, established his own logistics company, which is now running smoothly. His only concern now are his three daughters. His eldest daughter has immigrated overseas. His second daughter Hung Yeuk Shui has reached the marriageable age, but has no hopes for marriage anytime soon. She is constantly bickering with her younger sister Hung Sum Yue, who is an honour student, over trivial matters, causing their father to not know whether to laugh or cry. Hung Sue Yan, Hung Sue Gan's brother, moves in with the family, temporarily ending his life as a nomadic photographer. He joins Hung Yeuk Shui's company and encounters Ko Pak Fei, the director of an online shop. The two appear to be former lovers, making for lots of laughter. Since Hung Sue Yan moved in, a series of strange events have occurred in the family. Upon investigation, the source is traced to Lung Ging Fung, a promising young man who is the son of department store mogul Lung Gam Wai.",
					popularity: 1855.961,
					poster_path: "/lgD4j9gUGmMckZpWWRJjorWqGVT.jpg",
					vote_average: 3.4,
					vote_count: 11,
					media_type: "tv",
				},
				{
					backdrop_path: "/zaulpwl355dlKkvtAiSBE5LaoWA.jpg",
					first_air_date: "2010-10-31",
					genre_ids: [10759, 18, 10765],
					id: 1402,
					name: "The Walking Dead",
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Walking Dead",
					overview:
						"Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
					popularity: 1648.884,
					poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
					vote_average: 8.1,
					vote_count: 13737,
					media_type: "tv",
				},
				{
					backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
					first_air_date: "2011-04-17",
					genre_ids: [10765, 18, 10759],
					id: 1399,
					name: "Game of Thrones",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Game of Thrones",
					overview:
						"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
					popularity: 1116.986,
					poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
					vote_average: 8.4,
					vote_count: 19354,
					media_type: "tv",
				},
				{
					backdrop_path: "/2EwN8QwyJHIUtbWdfUU8Pohhk7N.jpg",
					first_air_date: "2019-10-28",
					genre_ids: [10765, 18],
					id: 86374,
					name: "War of the Worlds",
					origin_country: ["FR"],
					original_language: "en",
					original_name: "War of the Worlds",
					overview:
						"When astronomers detect a transmission from another galaxy, it is definitive proof of intelligent extra-terrestrial life. The world’s population waits for further contact with bated breath. They do not have to wait long. Within days, mankind is all but wiped out by a devastating attack; pockets of humanity are left in an eerily deserted world. As aliens hunt and kill those left alive, the survivors ask a burning question – who are these attackers and why are they hell-bent on our destruction?",
					popularity: 1078.353,
					poster_path: "/yThmbQkxSzW4HHdAaoj8RYHFH3i.jpg",
					vote_average: 7.4,
					vote_count: 717,
					media_type: "tv",
				},
				{
					backdrop_path: "/zymbuoBoL1i94xAOzVJF6IuWLfD.jpg",
					first_air_date: "2018-05-02",
					genre_ids: [10759, 18, 35],
					id: 77169,
					name: "Cobra Kai",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Cobra Kai",
					overview:
						"This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
					popularity: 1062.896,
					poster_path: "/m7tG5E1EbywuwTsl6hq990So0Bx.jpg",
					vote_average: 8.2,
					vote_count: 5159,
					media_type: "tv",
				},
				{
					backdrop_path: "/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg",
					first_air_date: "2016-01-25",
					genre_ids: [80, 10765],
					id: 63174,
					name: "Lucifer",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Lucifer",
					overview:
						"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
					popularity: 1006.98,
					poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
					vote_average: 8.5,
					vote_count: 12552,
					media_type: "tv",
				},
				{
					backdrop_path: "/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
					first_air_date: "2005-03-27",
					genre_ids: [18],
					id: 1416,
					name: "Grey's Anatomy",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Grey's Anatomy",
					overview:
						"Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
					popularity: 988.224,
					poster_path: "/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
					vote_average: 8.3,
					vote_count: 8479,
					media_type: "tv",
				},
				{
					backdrop_path: "/sUoiHP559kqz9fHb6McDPYdkTHO.jpg",
					first_air_date: "2011-10-05",
					genre_ids: [18, 9648, 10765],
					id: 1413,
					name: "American Horror Story",
					origin_country: ["US"],
					original_language: "en",
					original_name: "American Horror Story",
					overview:
						"An anthology horror drama series centering on different characters and locations, including a house with a murderous past, an asylum, a witch coven, a freak show, a hotel, a farmhouse in Roanoke, a cult, the apocalypse and a summer camp.",
					popularity: 965.522,
					poster_path: "/kxtWasoZ7Q92erTJuuRtZiXTPiH.jpg",
					vote_average: 8.1,
					vote_count: 4700,
					media_type: "tv",
				},
				{
					backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
					first_air_date: "2022-09-21",
					genre_ids: [10765, 10759, 10768],
					id: 83867,
					name: "Star Wars: Andor",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Star Wars: Andor",
					overview:
						"The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
					popularity: 958.367,
					poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
					vote_average: 7.9,
					vote_count: 119,
					media_type: "tv",
				},
				{
					backdrop_path: "/zNugnnR5KEmq9EzLcl0Me1UmHYk.jpg",
					first_air_date: "2022-04-09",
					genre_ids: [16, 35, 10759],
					id: 120089,
					name: "SPY x FAMILY",
					origin_country: ["JP"],
					original_language: "ja",
					original_name: "SPY×FAMILY",
					overview:
						"Master spy Twilight is the best at what he does when it comes to going undercover on dangerous missions in the name of a better world. But when he receives the ultimate impossible assignment—get married and have a kid—he may finally be in over his head! Not one to depend on others, Twilight has his work cut out for him procuring both a wife and a child for his mission to infiltrate an elite private school. What he doesn't know is that the wife he's chosen is an assassin and the child he's adopted is a telepath!",
					popularity: 887.328,
					poster_path: "/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
					vote_average: 8.7,
					vote_count: 788,
					media_type: "tv",
				},
				{
					backdrop_path: "/oc5IPML78INq4NPpjETysXme5Ck.jpg",
					first_air_date: "1989-12-17",
					genre_ids: [10751, 16, 35],
					id: 456,
					name: "The Simpsons",
					origin_country: ["US"],
					original_language: "en",
					original_name: "The Simpsons",
					overview:
						"Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
					popularity: 878.395,
					poster_path: "/zI3E2a3WYma5w8emI35mgq5Iurx.jpg",
					vote_average: 8,
					vote_count: 8269,
					media_type: "tv",
				},
				{
					backdrop_path: "/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg",
					first_air_date: "2022-08-22",
					genre_ids: [10766, 18],
					id: 204095,
					name: "Mar do Sertão",
					origin_country: ["BR"],
					original_language: "pt",
					original_name: "Mar do Sertão",
					overview: "",
					popularity: 855.46,
					poster_path: "/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg",
					vote_average: 4.5,
					vote_count: 11,
					media_type: "tv",
				},
				{
					backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
					first_air_date: "2016-07-15",
					genre_ids: [18, 10765, 9648],
					id: 66732,
					name: "Stranger Things",
					origin_country: ["US"],
					original_language: "en",
					original_name: "Stranger Things",
					overview:
						"When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
					popularity: 807.815,
					poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
					vote_average: 8.6,
					vote_count: 13907,
					media_type: "tv",
				},
				{
					backdrop_path: "/42iDbOtqWqPvI3FnP3KafLFrQq.jpg",
					first_air_date: "2022-10-07",
					genre_ids: [99, 80],
					id: 209167,
					name: "Conversations with a Killer: The Jeffrey Dahmer Tapes",
					origin_country: ["US"],
					original_language: "en",
					original_name:
						"Conversations with a Killer: The Jeffrey Dahmer Tapes",
					overview:
						"Serial killer Jeffrey Dahmer confesses to his gruesome crimes in unguarded interviews, offering an unsettling view into a disturbed mind.",
					popularity: 780.19,
					poster_path: "/5BTn4GxWL48BP8OkfiatxZ6qpuE.jpg",
					vote_average: 8.7,
					vote_count: 21,
					media_type: "tv",
				},
			],
			total_pages: 6902,
			total_results: 138028,
			media_type: "tv",
		},
		genres: [
			{
				id: 10759,
				name: "Action & Adventure",
			},
			{
				id: 16,
				name: "Animation",
			},
			{
				id: 35,
				name: "Comedy",
			},
			{
				id: 80,
				name: "Crime",
			},
			{
				id: 99,
				name: "Documentary",
			},
			{
				id: 18,
				name: "Drama",
			},
			{
				id: 10751,
				name: "Family",
			},
			{
				id: 10762,
				name: "Kids",
			},
			{
				id: 9648,
				name: "Mystery",
			},
			{
				id: 10763,
				name: "News",
			},
			{
				id: 10764,
				name: "Reality",
			},
			{
				id: 10765,
				name: "Sci-Fi & Fantasy",
			},
			{
				id: 10766,
				name: "Soap",
			},
			{
				id: 10767,
				name: "Talk",
			},
			{
				id: 10768,
				name: "War & Politics",
			},
			{
				id: 37,
				name: "Western",
			},
		],
	},
	trending: {
		page: 1,
		results: [
			{
				adult: false,
				backdrop_path: "/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg",
				id: 894205,
				title: "Werewolf by Night",
				original_language: "en",
				original_title: "Werewolf by Night",
				overview:
					"On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.",
				poster_path: "/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
				media_type: "movie",
				genre_ids: [28, 14, 27, 9648],
				popularity: 132.943,
				release_date: "2022-09-25",
				video: false,
				vote_average: 7.503,
				vote_count: 187,
			},
			{
				adult: false,
				backdrop_path: "/iHc14vucwUMl6WuvQa4iPfoEdy9.jpg",
				id: 799546,
				title: "Luckiest Girl Alive",
				original_language: "en",
				original_title: "Luckiest Girl Alive",
				overview:
					"A successful woman in New York City finds her life upended when she is forced to confront a dark truth that threatens to unravel her meticulously crafted life.",
				poster_path: "/e0vrbTmTf2ZcW5CIS9qJ8FDbsU9.jpg",
				media_type: "movie",
				genre_ids: [80, 18],
				popularity: 43.798,
				release_date: "2022-09-30",
				video: false,
				vote_average: 6.389,
				vote_count: 54,
			},
			{
				adult: false,
				backdrop_path: "/3r3tZgKTw1554hcFoUfydLHE38w.jpg",
				id: 338947,
				title: "Hellraiser",
				original_language: "en",
				original_title: "Hellraiser",
				overview:
					"A young woman struggling with addiction comes into possession of an ancient puzzle box, unaware that its purpose is to summon the Cenobites, a group of sadistic supernatural beings from another dimension.",
				poster_path: "/u4ikorO4E3PouLRRwGaRuhFvsl3.jpg",
				media_type: "movie",
				genre_ids: [27, 9648],
				popularity: 124.915,
				release_date: "2022-09-28",
				video: false,
				vote_average: 6.701,
				vote_count: 82,
			},
			{
				adult: false,
				backdrop_path: "/jGcACEQ684x0C6jRlBrkEJyVm9m.jpg",
				id: 126254,
				name: "The Midnight Club",
				original_language: "en",
				original_name: "The Midnight Club",
				overview:
					"At a manor with a mysterious history, the 8 members of the Midnight Club meet each night at midnight to tell sinister stories – and to look for signs of the supernatural from the beyond.",
				poster_path: "/2Y4F9BHkacKIMnDBZI3GGKpG1If.jpg",
				media_type: "tv",
				genre_ids: [18, 9648],
				popularity: 87.417,
				first_air_date: "2022-10-07",
				vote_average: 7.7,
				vote_count: 16,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
				id: 84773,
				name: "The Lord of the Rings: The Rings of Power",
				original_language: "en",
				original_name: "The Lord of the Rings: The Rings of Power",
				overview:
					"Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
				poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
				media_type: "tv",
				genre_ids: [10765, 10759, 18],
				popularity: 5653.246,
				first_air_date: "2022-09-01",
				vote_average: 7.669,
				vote_count: 977,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/iiaU8m4kUyDnbqtlr2hyiXYUlcH.jpg",
				id: 723419,
				title: "Mr. Harrigan's Phone",
				original_language: "en",
				original_title: "Mr. Harrigan's Phone",
				overview:
					"Craig, a young boy living in a small town befriends an older, reclusive billionaire, Mr. Harrigan. The two form a bond over books and an iPhone, but when the man passes away the boy discovers that not everything dead is gone.",
				poster_path: "/gPn9e8eP7TeKQU4IeWAMzOajR40.jpg",
				media_type: "movie",
				genre_ids: [53, 18],
				popularity: 289.138,
				release_date: "2022-10-05",
				video: false,
				vote_average: 6.724,
				vote_count: 156,
			},
			{
				adult: false,
				backdrop_path: "/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg",
				id: 718930,
				title: "Bullet Train",
				original_language: "en",
				original_title: "Bullet Train",
				overview:
					"Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
				poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
				media_type: "movie",
				genre_ids: [28, 35, 53],
				popularity: 4647.01,
				release_date: "2022-07-03",
				video: false,
				vote_average: 7.481,
				vote_count: 1568,
			},
			{
				adult: false,
				backdrop_path: "/7t5ALGBUOHafXpf25sXDLjm0GNt.jpg",
				id: 795109,
				title: "Catherine Called Birdy",
				original_language: "en",
				original_title: "Catherine Called Birdy",
				overview:
					"A teenage girl in Medieval England navigates life and tries to avoid the arranged marriages her father maps out for her.",
				poster_path: "/a6welBP7DtjHDsr6fwT5IuCS33f.jpg",
				media_type: "movie",
				genre_ids: [12, 35],
				popularity: 23.363,
				release_date: "2022-09-23",
				video: false,
				vote_average: 5.7,
				vote_count: 9,
			},
			{
				adult: false,
				backdrop_path: "/et1rWV1LCt4ViKB9eQWOVvnxJwS.jpg",
				id: 999722,
				title: "Old People",
				original_language: "de",
				original_title: "Old People",
				overview:
					"A woman who's returned home with her two kids to attend her sister's wedding must suddenly defend their lives against older people on a killing spree.",
				poster_path: "/nSguJmHeYv6cwTljOZduPJDTweS.jpg",
				media_type: "movie",
				genre_ids: [27],
				popularity: 50.366,
				release_date: "2022-10-07",
				video: false,
				vote_average: 6.08,
				vote_count: 25,
			},
			{
				adult: false,
				backdrop_path: "/3O5voBAoeQ9kipZCKmx6uDfiRLc.jpg",
				id: 136699,
				name: "Glitch",
				original_language: "ko",
				original_name: "글리치",
				overview:
					"A young woman joins forces with a UFO enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy.",
				poster_path: "/dspwDOosidQT85oPDDHMM9zmaLw.jpg",
				media_type: "tv",
				genre_ids: [18, 35, 9648, 10765],
				popularity: 83.255,
				first_air_date: "2022-10-07",
				vote_average: 7.8,
				vote_count: 5,
				origin_country: ["KR"],
			},
			{
				adult: false,
				backdrop_path: "/gTkheiyTGscbDuJgh78hEZmiKnD.jpg",
				id: 901385,
				title: "Significant Other",
				original_language: "en",
				original_title: "Significant Other",
				overview:
					"Ruth and Harry decide to take a romantic backpacking trip through the Pacific Northwest, but amongst the beautiful scenery, Ruth makes an unexpected discovery that sets her off on a strange, frightening new path. The couple aren't alone in the woods, and they might not be the same when they come out...if they come out.",
				poster_path: "/liGvBdUsyOfiTJjNCD55JJfISzb.jpg",
				media_type: "movie",
				genre_ids: [878, 53, 27, 10749],
				popularity: 76.719,
				release_date: "2022-10-06",
				video: false,
				vote_average: 6.775,
				vote_count: 20,
			},
			{
				adult: false,
				backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
				id: 94997,
				name: "House of the Dragon",
				original_language: "en",
				original_name: "House of the Dragon",
				overview:
					"The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
				poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
				media_type: "tv",
				genre_ids: [10765, 18, 10759],
				popularity: 5631.599,
				first_air_date: "2022-08-21",
				vote_average: 8.556,
				vote_count: 1645,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
				id: 642885,
				title: "Hocus Pocus 2",
				original_language: "en",
				original_title: "Hocus Pocus 2",
				overview:
					"It’s been 29 years since someone lit the Black Flame Candle and resurrected the 17th-century sisters, and they are looking for revenge. Now it is up to three high-school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow’s Eve.",
				poster_path: "/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg",
				media_type: "movie",
				genre_ids: [14, 35, 10751],
				popularity: 5947.971,
				release_date: "2022-09-27",
				video: false,
				vote_average: 7.794,
				vote_count: 529,
			},
			{
				adult: false,
				backdrop_path: "/eljErfkQUcFUgQkI4I1soZcH8MW.jpg",
				id: 92783,
				name: "She-Hulk: Attorney at Law",
				original_language: "en",
				original_name: "She-Hulk: Attorney at Law",
				overview:
					"Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
				poster_path: "/3qO7wycn6o0lUJf15dupMFbEBTY.jpg",
				media_type: "tv",
				genre_ids: [35, 10765],
				popularity: 3661.228,
				first_air_date: "2022-08-18",
				vote_average: 7.027,
				vote_count: 905,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
				id: 616037,
				title: "Thor: Love and Thunder",
				original_language: "en",
				original_title: "Thor: Love and Thunder",
				overview:
					"After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
				poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
				media_type: "movie",
				genre_ids: [14, 28, 35],
				popularity: 1920.283,
				release_date: "2022-07-06",
				video: false,
				vote_average: 6.751,
				vote_count: 4093,
			},
			{
				adult: false,
				backdrop_path: "/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg",
				id: 717728,
				title: "Jeepers Creepers: Reborn",
				original_language: "en",
				original_title: "Jeepers Creepers: Reborn",
				overview:
					"Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.",
				poster_path: "/aGBuiirBIQ7o64FmJxO53eYDuro.jpg",
				media_type: "movie",
				genre_ids: [27, 53, 9648],
				popularity: 869.691,
				release_date: "2022-09-15",
				video: false,
				vote_average: 5.656,
				vote_count: 167,
			},
			{
				adult: false,
				backdrop_path: "/sobIeWp1a3saZTBkoRTAf8sfC7J.jpg",
				id: 335795,
				title: "Monster High: The Movie",
				original_language: "en",
				original_title: "Monster High: The Movie",
				overview:
					"Clawdeen Wolf, half human and half werewolf, has recently started attending Monster High, a school for monsters in all forms. After quickly befriending her classmates Frankie Stein and Draculaura, Clawdeen feels like she has finally found a place where she can truly be herself, or so she thinks. Soon, a devious plan to destroy Monster High threatens to reveal her real identity and Clawdeen must learn to embrace her true monster heart before it's too late.",
				poster_path: "/tn3GWm0Erehkpur8PUuYWxGpul5.jpg",
				media_type: "movie",
				genre_ids: [12, 10751, 10770],
				popularity: 204.093,
				release_date: "2022-10-06",
				video: false,
				vote_average: 6.474,
				vote_count: 38,
			},
			{
				adult: false,
				backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
				id: 83867,
				name: "Star Wars: Andor",
				original_language: "en",
				original_name: "Star Wars: Andor",
				overview:
					"The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
				poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
				media_type: "tv",
				genre_ids: [10765, 10759, 10768],
				popularity: 958.367,
				first_air_date: "2022-09-21",
				vote_average: 7.9,
				vote_count: 119,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/mVNPfpydornVe4H4UCIk7WevWjf.jpg",
				id: 882598,
				title: "Smile",
				original_language: "en",
				original_title: "Smile",
				overview:
					"After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
				poster_path: "/hiaeZKzwsk4y4atFhmncO5KRxeT.jpg",
				media_type: "movie",
				genre_ids: [27, 9648, 53],
				popularity: 2015.942,
				release_date: "2022-09-23",
				video: false,
				vote_average: 6.903,
				vote_count: 145,
			},
			{
				adult: false,
				backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
				id: 113988,
				name: "Dahmer – Monster: The Jeffrey Dahmer Story",
				original_language: "en",
				original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
				overview:
					"Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?",
				poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
				media_type: "tv",
				genre_ids: [18, 80],
				popularity: 9719.599,
				first_air_date: "2022-09-21",
				vote_average: 8.366,
				vote_count: 699,
				origin_country: ["US"],
			},
		],
		total_pages: 1000,
		total_results: 20000,
	},
	trendingWeekly: {
		page: 1,
		results: [
			{
				adult: false,
				backdrop_path: "/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg",
				id: 718930,
				title: "Bullet Train",
				original_language: "en",
				original_title: "Bullet Train",
				overview:
					"Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
				poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
				media_type: "movie",
				genre_ids: [28, 35, 53],
				popularity: 4647.01,
				release_date: "2022-07-03",
				video: false,
				vote_average: 7.481,
				vote_count: 1568,
			},
			{
				adult: false,
				backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
				id: 84773,
				name: "The Lord of the Rings: The Rings of Power",
				original_language: "en",
				original_name: "The Lord of the Rings: The Rings of Power",
				overview:
					"Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
				poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
				media_type: "tv",
				genre_ids: [10765, 10759, 18],
				popularity: 5653.246,
				first_air_date: "2022-09-01",
				vote_average: 7.669,
				vote_count: 977,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
				id: 642885,
				title: "Hocus Pocus 2",
				original_language: "en",
				original_title: "Hocus Pocus 2",
				overview:
					"It’s been 29 years since someone lit the Black Flame Candle and resurrected the 17th-century sisters, and they are looking for revenge. Now it is up to three high-school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow’s Eve.",
				poster_path: "/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg",
				media_type: "movie",
				genre_ids: [14, 35, 10751],
				popularity: 5947.971,
				release_date: "2022-09-27",
				video: false,
				vote_average: 7.794,
				vote_count: 528,
			},
			{
				adult: false,
				backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
				id: 94997,
				name: "House of the Dragon",
				original_language: "en",
				original_name: "House of the Dragon",
				overview:
					"The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
				poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
				media_type: "tv",
				genre_ids: [10765, 18, 10759],
				popularity: 5631.599,
				first_air_date: "2022-08-21",
				vote_average: 8.556,
				vote_count: 1645,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
				id: 616037,
				title: "Thor: Love and Thunder",
				original_language: "en",
				original_title: "Thor: Love and Thunder",
				overview:
					"After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
				poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
				media_type: "movie",
				genre_ids: [14, 28, 35],
				popularity: 1920.283,
				release_date: "2022-07-06",
				video: false,
				vote_average: 6.75,
				vote_count: 4092,
			},
			{
				adult: false,
				backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
				id: 83867,
				name: "Star Wars: Andor",
				original_language: "en",
				original_name: "Star Wars: Andor",
				overview:
					"The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
				poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
				media_type: "tv",
				genre_ids: [10765, 10759, 10768],
				popularity: 958.367,
				first_air_date: "2022-09-21",
				vote_average: 7.9,
				vote_count: 119,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg",
				id: 894205,
				title: "Werewolf by Night",
				original_language: "en",
				original_title: "Werewolf by Night",
				overview:
					"On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.",
				poster_path: "/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
				media_type: "movie",
				genre_ids: [28, 14, 27, 9648],
				popularity: 132.943,
				release_date: "2022-09-25",
				video: false,
				vote_average: 7.489,
				vote_count: 186,
			},
			{
				adult: false,
				backdrop_path: "/o5Uy3zM1SNxzoMwy5H04GQAmfNF.jpg",
				id: 301502,
				title: "Blonde",
				original_language: "en",
				original_title: "Blonde",
				overview:
					"From her volatile childhood as Norma Jeane, through her rise to stardom and romantic entanglements, this reimagined fictional portrait of Hollywood legend Marilyn Monroe blurs the lines of fact and fiction to explore the widening split between her public and private selves.",
				poster_path: "/jOgbnL5FB30pprEjZaY1E1iPtPM.jpg",
				media_type: "movie",
				genre_ids: [18],
				popularity: 766.136,
				release_date: "2022-09-16",
				video: false,
				vote_average: 6.587,
				vote_count: 461,
			},
			{
				adult: false,
				backdrop_path: "/eljErfkQUcFUgQkI4I1soZcH8MW.jpg",
				id: 92783,
				name: "She-Hulk: Attorney at Law",
				original_language: "en",
				original_name: "She-Hulk: Attorney at Law",
				overview:
					"Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
				poster_path: "/3qO7wycn6o0lUJf15dupMFbEBTY.jpg",
				media_type: "tv",
				genre_ids: [35, 10765],
				popularity: 3661.228,
				first_air_date: "2022-08-18",
				vote_average: 7.027,
				vote_count: 905,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/z8KsgBFtduX5bS1yVkjoGo4L7KJ.jpg",
				id: 597922,
				title: "The Greatest Beer Run Ever",
				original_language: "en",
				original_title: "The Greatest Beer Run Ever",
				overview:
					"Chickie wants to support his friends fighting in Vietnam, so he does something wild—personally bring them American beer. What starts as a well-meaning journey quickly changes Chickie’s life and perspective. Based on a true story.",
				poster_path: "/ggf37TpcKaxwguhvtNn6MQpyqBn.jpg",
				media_type: "movie",
				genre_ids: [18, 35, 10752],
				popularity: 1233.579,
				release_date: "2022-09-30",
				video: false,
				vote_average: 7.796,
				vote_count: 157,
			},
			{
				adult: false,
				backdrop_path: "/5vUux2vNUTqwCzb7tVcH18XnsF.jpg",
				id: 113988,
				name: "Dahmer – Monster: The Jeffrey Dahmer Story",
				original_language: "en",
				original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
				overview:
					"Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?",
				poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
				media_type: "tv",
				genre_ids: [18, 80],
				popularity: 9719.599,
				first_air_date: "2022-09-21",
				vote_average: 8.366,
				vote_count: 699,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/3r3tZgKTw1554hcFoUfydLHE38w.jpg",
				id: 338947,
				title: "Hellraiser",
				original_language: "en",
				original_title: "Hellraiser",
				overview:
					"A young woman struggling with addiction comes into possession of an ancient puzzle box, unaware that its purpose is to summon the Cenobites, a group of sadistic supernatural beings from another dimension.",
				poster_path: "/u4ikorO4E3PouLRRwGaRuhFvsl3.jpg",
				media_type: "movie",
				genre_ids: [27, 9648],
				popularity: 124.915,
				release_date: "2022-09-28",
				video: false,
				vote_average: 6.701,
				vote_count: 82,
			},
			{
				adult: false,
				backdrop_path: "/iHc14vucwUMl6WuvQa4iPfoEdy9.jpg",
				id: 799546,
				title: "Luckiest Girl Alive",
				original_language: "en",
				original_title: "Luckiest Girl Alive",
				overview:
					"A successful woman in New York City finds her life upended when she is forced to confront a dark truth that threatens to unravel her meticulously crafted life.",
				poster_path: "/e0vrbTmTf2ZcW5CIS9qJ8FDbsU9.jpg",
				media_type: "movie",
				genre_ids: [80, 18],
				popularity: 43.798,
				release_date: "2022-09-30",
				video: false,
				vote_average: 6.389,
				vote_count: 54,
			},
			{
				adult: false,
				backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
				id: 361743,
				title: "Top Gun: Maverick",
				original_language: "en",
				original_title: "Top Gun: Maverick",
				overview:
					"After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
				poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
				media_type: "movie",
				genre_ids: [28, 18],
				popularity: 1341.236,
				release_date: "2022-05-24",
				video: false,
				vote_average: 8.36,
				vote_count: 4199,
			},
			{
				adult: false,
				backdrop_path: "/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg",
				id: 717728,
				title: "Jeepers Creepers: Reborn",
				original_language: "en",
				original_title: "Jeepers Creepers: Reborn",
				overview:
					"Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.",
				poster_path: "/aGBuiirBIQ7o64FmJxO53eYDuro.jpg",
				media_type: "movie",
				genre_ids: [27, 53, 9648],
				popularity: 869.691,
				release_date: "2022-09-15",
				video: false,
				vote_average: 5.656,
				vote_count: 167,
			},
			{
				adult: false,
				backdrop_path: "/dxihDyyA6RSAtLZog4l1MYdDqLD.jpg",
				id: 976720,
				title: "Vesper",
				original_language: "en",
				original_title: "Vesper",
				overview:
					"After the collapse of Earth's ecosystem, Vesper, a 13-year-old girl struggling to survive with her paralyzed Father, meets a mysterious Woman with a secret that forces Vesper to use her wits, strength and bio-hacking abilities to fight for the possibility of a future.",
				poster_path: "/rLrfEvJhQP3SubJR9SYwHWE9tlZ.jpg",
				media_type: "movie",
				genre_ids: [878, 18, 12],
				popularity: 102.939,
				release_date: "2022-08-17",
				video: false,
				vote_average: 6.996,
				vote_count: 118,
			},
			{
				adult: false,
				backdrop_path: "/iiaU8m4kUyDnbqtlr2hyiXYUlcH.jpg",
				id: 723419,
				title: "Mr. Harrigan's Phone",
				original_language: "en",
				original_title: "Mr. Harrigan's Phone",
				overview:
					"Craig, a young boy living in a small town befriends an older, reclusive billionaire, Mr. Harrigan. The two form a bond over books and an iPhone, but when the man passes away the boy discovers that not everything dead is gone.",
				poster_path: "/gPn9e8eP7TeKQU4IeWAMzOajR40.jpg",
				media_type: "movie",
				genre_ids: [53, 18],
				popularity: 289.138,
				release_date: "2022-10-05",
				video: false,
				vote_average: 6.724,
				vote_count: 156,
			},
			{
				adult: false,
				backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
				id: 744276,
				title: "After Ever Happy",
				original_language: "en",
				original_title: "After Ever Happy",
				overview:
					"As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
				poster_path: "/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg",
				media_type: "movie",
				genre_ids: [10749, 18],
				popularity: 2785.246,
				release_date: "2022-08-24",
				video: false,
				vote_average: 6.879,
				vote_count: 323,
			},
			{
				adult: false,
				backdrop_path: "/jGcACEQ684x0C6jRlBrkEJyVm9m.jpg",
				id: 126254,
				name: "The Midnight Club",
				original_language: "en",
				original_name: "The Midnight Club",
				overview:
					"At a manor with a mysterious history, the 8 members of the Midnight Club meet each night at midnight to tell sinister stories – and to look for signs of the supernatural from the beyond.",
				poster_path: "/2Y4F9BHkacKIMnDBZI3GGKpG1If.jpg",
				media_type: "tv",
				genre_ids: [18, 9648],
				popularity: 87.417,
				first_air_date: "2022-10-07",
				vote_average: 7.7,
				vote_count: 16,
				origin_country: ["US"],
			},
			{
				adult: false,
				backdrop_path: "/vZujZnmkYB5nGUC5d5llK9DbGLk.jpg",
				id: 505642,
				title: "Black Panther: Wakanda Forever",
				original_language: "en",
				original_title: "Black Panther: Wakanda Forever",
				overview:
					"Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
				poster_path: "/bxCTPBtVduUotUqKMBgz6lJQUJi.jpg",
				media_type: "movie",
				genre_ids: [28, 12, 878],
				popularity: 228.421,
				release_date: "2022-11-09",
				video: false,
				vote_average: 0,
				vote_count: 0,
			},
		],
		total_pages: 1000,
		total_results: 20000,
	},
	watchList: {
		results: [
			{
				adult: false,
				backdrop_path: "/iiaU8m4kUyDnbqtlr2hyiXYUlcH.jpg",
				belongs_to_collection: null,
				budget: 0,
				genres: [
					{
						id: 53,
						name: "Thriller",
					},
					{
						id: 18,
						name: "Drama",
					},
				],
				homepage: "https://www.netflix.com/title/81288353",
				id: 723419,
				imdb_id: "tt12908110",
				original_language: "en",
				original_title: "Mr. Harrigan's Phone",
				overview:
					"Craig, a young boy living in a small town befriends an older, reclusive billionaire, Mr. Harrigan. The two form a bond over books and an iPhone, but when the man passes away the boy discovers that not everything dead is gone.",
				popularity: 289.138,
				poster_path: "/gPn9e8eP7TeKQU4IeWAMzOajR40.jpg",
				production_companies: [
					{
						id: 3172,
						logo_path: "/kDedjRZwO8uyFhuHamomOhN6fzG.png",
						name: "Blumhouse Productions",
						origin_country: "US",
					},
					{
						id: 19328,
						logo_path: "/2AdkrU1av4fDGw0Zaf68XH4YcqC.png",
						name: "Ryan Murphy Productions",
						origin_country: "US",
					},
				],
				production_countries: [
					{
						iso_3166_1: "US",
						name: "United States of America",
					},
				],
				release_date: "2022-10-05",
				revenue: 0,
				runtime: 105,
				spoken_languages: [
					{
						english_name: "English",
						iso_639_1: "en",
						name: "English",
					},
				],
				status: "Released",
				tagline: "Some connections never die.",
				title: "Mr. Harrigan's Phone",
				video: false,
				vote_average: 6.723,
				vote_count: 150,
				media_type: "movie",
			},
			{
				adult: false,
				backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
				belongs_to_collection: {
					id: 702624,
					name: "After Collection",
					poster_path: "/250ewaLutOJXqBBqMKxCHD1KpCL.jpg",
					backdrop_path: "/zZTy8G3sEVZNv0yGssgc7DvPUQJ.jpg",
				},
				budget: 0,
				genres: [
					{
						id: 10749,
						name: "Romance",
					},
					{
						id: 18,
						name: "Drama",
					},
				],
				homepage: "",
				id: 744276,
				imdb_id: "tt13070038",
				original_language: "en",
				original_title: "After Ever Happy",
				overview:
					"As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
				popularity: 2785.246,
				poster_path: "/qRkL0y2KFx97Gh9cK7cKKhL1Ej1.jpg",
				production_companies: [
					{
						id: 6626,
						logo_path: "/A1BnMoWjzjOrjzpWimyBQkf84mS.png",
						name: "Voltage Pictures",
						origin_country: "US",
					},
					{
						id: 88606,
						logo_path: "/3w49QoRwptUujWxSjcR3iEr1XSU.png",
						name: "Vertical Entertainment",
						origin_country: "US",
					},
					{
						id: 107107,
						logo_path: null,
						name: "CalMaple Films",
						origin_country: "US",
					},
					{
						id: 107108,
						logo_path: "/5mxc7uNtFOZm2ly0BxixxGPvPlb.png",
						name: "Wattpad",
						origin_country: "US",
					},
					{
						id: 158529,
						logo_path: null,
						name: "Ethea Entertainment",
						origin_country: "US",
					},
				],
				production_countries: [
					{
						iso_3166_1: "US",
						name: "United States of America",
					},
				],
				release_date: "2022-08-24",
				revenue: 0,
				runtime: 95,
				spoken_languages: [
					{
						english_name: "English",
						iso_639_1: "en",
						name: "English",
					},
				],
				status: "Released",
				tagline: "",
				title: "After Ever Happy",
				video: false,
				vote_average: 6.879,
				vote_count: 321,
				media_type: "movie",
			},
		],
	},
};
export default movieDataMock;
