// Has the locations for all the possible profile images a user can have
const LOCATION_PREFIX = "/stockphotos/";
const globalProfileImage = [
	LOCATION_PREFIX + "cat1.jpg",
	LOCATION_PREFIX + "cat2.jpg",
	LOCATION_PREFIX + "cat3.jpg",
	LOCATION_PREFIX + "cat4.jpg",
	LOCATION_PREFIX + "cat5.jpg",
	LOCATION_PREFIX + "cat6.jpg",
	LOCATION_PREFIX + "dog1.jpg",
	LOCATION_PREFIX + "dog2.jpg",
	LOCATION_PREFIX + "dog3.jpg",
	LOCATION_PREFIX + "dog4.jpg",
	LOCATION_PREFIX + "bird1.jpg",
	LOCATION_PREFIX + "bird2.jpg",
	LOCATION_PREFIX + "bird3.jpg",
	LOCATION_PREFIX + "bird4.jpg",
	LOCATION_PREFIX + "bird5.jpg",
	LOCATION_PREFIX + "bird6.jpg",
	LOCATION_PREFIX + "bird7.jpg",
	LOCATION_PREFIX + "goat1.jpg",
	LOCATION_PREFIX + "goat2.jpg",
	LOCATION_PREFIX + "goat3.jpg",
	LOCATION_PREFIX + "insect1.jpg",
	LOCATION_PREFIX + "insect2.jpg",
	LOCATION_PREFIX + "insect3.jpg",
	LOCATION_PREFIX + "insect4.jpg",
	LOCATION_PREFIX + "insect5.jpg",
	LOCATION_PREFIX + "jellyfish1.jpg",
	LOCATION_PREFIX + "jellyfish2.jpg",
	LOCATION_PREFIX + "racoon1.jpg",
	LOCATION_PREFIX + "rodent1.jpg",
	LOCATION_PREFIX + "rodent2.jpg",
	LOCATION_PREFIX + "rodent3.jpg",
];

export default globalProfileImage;
